orders/urls.py
from django.urls import path
from .views import checkout_base, created_order, checkout_edit

urlpatterns = [
    path('checkout_base', checkout_base, name='checkout_base'),
    path('created_order', created_order, name='created_order'),
    path('checkout_edit/<product_id>', checkout_edit, name='checkout_edit'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('sweet.urls', 'sweet'), namespace='sweet')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from sweet.models import Product, Adress


class Order(models.Model):
    country = models.CharField(max_length=30, blank=True)
    city = models.CharField(max_length=30, blank=True)
    street = models.CharField(max_length=50, blank=True)
    house = models.CharField(max_length=30, blank=True)
    post_index = models.CharField(max_length=30, blank=True)
    delivery_time = models.CharField(blank=False, max_length=20)
    comment = models.TextField(max_length=250, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, null=True, on_delete=models.SET_NULL, related_name='items')
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL, related_name='order_items')
    price = models.IntegerField()
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['country', 'city', 'street', 'house', 'post_index', 'delivery_time', 'comment']

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import OrderItem, Order
from sweet.models import Product
from .forms import OrderCreateForm
from cart.cart import Cart
from django.views.decorators.http import require_POST
from cart.forms import CartAddEditProductForm


@require_POST
def checkout_edit(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddEditProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=not cd['update'])
    return redirect('orders:checkout_base')


def checkout_base(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            return render(request, 'created_order.html',
                          {'order': order})
    else:
        cart_product_form = CartAddEditProductForm()
        form = OrderCreateForm()
    return render(request, 'checkout_base.html',
                  {'cart': cart, 'form': form, 'cart_product_form': cart_product_form})


def created_order(request):
    return render(request, 'created_order.html')

orders/templates/checkout_base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<h1>Ваш заказ:</h1>

    <div class="order-info">
        <style>
   table {
    width: 30%; /* Ширина таблицы */
    border: 4px double black; /* Рамка вокруг таблицы */
    border-collapse: collapse; /* Отображать только одинарные линии */
   }
   th {
    text-align: left; /* Выравнивание по левому краю */
    background: #ccc; /* Цвет фона ячеек */
    padding: 5px; /* Поля вокруг содержимого ячеек */
    border: 1px solid black; /* Граница вокруг ячеек */
   }
   td {
    padding: 5px; /* Поля вокруг содержимого ячеек */
    border: 1px solid black; /* Граница вокруг ячеек */
   }
  </style>
        <table>
            <tr>
        <h3></h3>
        <ul>
            {% for item in cart %}

                    <tr><td>{{ item.product.name }}</td></tr>
                   <tr><td> {{ item.quantity }}шт</td></tr>
                   <tr><td> <span>${{ item.total_price }}</span></td></tr>

                   <tr> <td><form action="{% url 'orders:checkout_edit' item.product.id %}" method="post">
                        {{ cart_product_form.as_p }}
                        {% csrf_token %}
                        <input type="submit" value="Изменить количество {{item.product.name}}">
                    </form></td></tr>

            {% endfor %}
        </ul>
        <tr><td><p>Total: ${{ cart.get_total_price }}</p></td></tr>
            </table>
    </div>



    <form action="{% url 'orders:checkout_base'%}" method="post" class="order-form">
        {{ form.as_p }}
        <h3><input type="submit" value="Разместить заказ"></h3>
        {% csrf_token %}
    </form>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

orders/templates/created_order.html
{% extends "base.html" %}

{% block title %}{% endblock %}

{% block content %}
    <h1>Thank you</h1>
    <p>Your order has been successfully completed. Your order number is
        <strong>{{ order.id }}</strong>.</p>
{% endblock %}