cart/urls.py
from django.urls import path
from .views import basket, basket_remove, basket_add

urlpatterns = [
    path('basket', basket, name='basket'),
    path('basket_remove/<product_id>', basket_remove, name='basket_remove'),
    path('basket_add/<product_id>', basket_add, name='basket_add'),
]

orders/urls.py
from django.urls import path
from .views import checkout_base, created_order, checkout_edit

urlpatterns = [
    path('checkout_base', checkout_base, name='checkout_base'),
    path('created_order', created_order, name='created_order'),
    path('checkout_edit/<product_id>', checkout_edit, name='checkout_edit'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('sweet.urls', 'sweet'), namespace='sweet')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from sweet.models import Adress

PRODUCT_QUANTITY_CHOICES = ((i, str(i)) for i in range(1, 21))


class CartAddEditProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from sweet.models import Product, Adress
from .cart import Cart
from .forms import CartAddEditProductForm


def basket(request):
    cart = Cart(request)
    return render(request, 'basket.html', {'cart': cart})


@require_POST
def checkout_edit(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddEditProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=not cd['update'])
    return redirect('checkout_base')


@require_POST
def basket_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddEditProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:basket')


def basket_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:basket')

cart/templates/basket.html
{% block title %}
{% endblock %}
{% block content %}
    <h1>Корзина</h1>
 <style>
   table {
    width: 100%; /* Ширина таблицы */
    border: 4px double black; /* Рамка вокруг таблицы */
    border-collapse: collapse; /* Отображать только одинарные линии */
   }
   th {
    text-align: left; /* Выравнивание по левому краю */
    background: #ccc; /* Цвет фона ячеек */
    padding: 5px; /* Поля вокруг содержимого ячеек */
    border: 1px solid black; /* Граница вокруг ячеек */
   }
   td {
    padding: 5px; /* Поля вокруг содержимого ячеек */
    border: 1px solid black; /* Граница вокруг ячеек */
   }
  </style>
    <table class="cart" >
        <thead>
        <tr>
            <th>Товар</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Цена за шт</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart:basket_remove' product.id%}">Remove</a></td>
                    <td class="num">${{ item.price }}</td>

                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="/" class="button light">Продолжить покупки</a>

        <a href="{% url 'orders:checkout_base' %}" class="button">Оформить заказ</a>
    </p>
{% endblock %}