cart/urls.py
from django.urls import path
from .views import basket, basket_remove, basket_add

urlpatterns = [
    path('basket', basket, name='basket'),
    path('basket_remove/<product_id>', basket_remove, name='basket_remove'),
    path('basket_add/<product_id>', basket_add, name='basket_add'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('', include(('sweet.urls', 'sweet'), namespace='sweet')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sweet/urls.py
from django.urls import path
from django.conf.urls import url
from .views import home, category_page, product_page


urlpatterns = [
    path('', home, name='home'),
    path('category_page/<category_id>', category_page, name='category_page'),
    path('product_page/<product_id>', product_page, name='product_page'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
</head>
<body>
<div id="header">
    <a href="/" class="logo">На главную</a>
</div>
<div id="subheader">
    <div class="cart">
    {% with total_items=cart|length %}
        {% if cart|length > 0 %}
            Your cart:
            <a href="{% url 'cart:basket' %}">
                {{ total_items }} item{{ total_items|pluralize }},
                ${{ cart.get_total_price }}
            </a>
        {% else %}
            Your cart is empty.
        {% endif %}
    {% endwith %}
</div>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/categories.html
{% extends "base.html" %}

{% block content %}

{% if all_categories %}

    {% for category in all_categories %}

        {% csrf_token %}
<style>
   table {
    width: 20%; /* Ширина таблицы */
    border: 4px double black; /* Рамка вокруг таблицы */
    border-collapse: collapse; /* Отображать только одинарные линии */
   }
   th {
    text-align: left; /* Выравнивание по левому краю */
    background: #ccc; /* Цвет фона ячеек */
    padding: 5px; /* Поля вокруг содержимого ячеек */
    border: 1px solid black; /* Граница вокруг ячеек */
   }
   td {
    padding: 5px; /* Поля вокруг содержимого ячеек */
    border: 1px solid black; /* Граница вокруг ячеек */
   }
  </style>
    <table class="category_page" >

         <tr>
             <td ><a href="{% url 'sweet:category_page' category.id %}">{{category.name}}</a></td>
         </tr>

    </table>


    {% endfor %}

{% endif %}

{% csrf_token %}
    <form class="container" action="{% url 'cart:basket' %}">

      <button>Перейти в корзину</button>
    </form>

{% endblock %}

templates/category_page.html
{% block title %}{% endblock %}


{% block content %}

{% if all_products %}

    {% for product in all_products %}

        {% csrf_token %}
         <tr>
             <td ><a href="{% url 'sweet:product_page' product.id %}">{{product.name}}</a></td>
         </tr>

    {% endfor %}

<form class="container" action="{% url 'sweet:home' %}">
      <button>Продолжить покупки</button>
</form>
<form class="container" action="{% url 'cart:basket' %}">
      <button>Перейти в корзину</button>
</form>

{% endif %}

{% endblock %}

templates/product_page.html
{% extends "base.html" %}
{% block title %}{% endblock %}

{% block content %}

{% if product %}

        {% csrf_token %}
<style>
   table {
    width: 50%; /* Ширина таблицы */
    border: 4px double black; /* Рамка вокруг таблицы */
    border-collapse: collapse; /* Отображать только одинарные линии */
   }
   th {
    text-align: left; /* Выравнивание по левому краю */
    background: #ccc; /* Цвет фона ячеек */
    padding: 5px; /* Поля вокруг содержимого ячеек */
    border: 1px solid black; /* Граница вокруг ячеек */
   }
   td {
    padding: 5px; /* Поля вокруг содержимого ячеек */
    border: 1px solid black; /* Граница вокруг ячеек */
   }
  </style>


    <table class="category_page" >
        <thead>
        <tr>
            <th>Товар</th>
            <th>Описание</th>
            <th>Цена за шт</th>
        </tr>
        </thead>
        <tbody>
         <tr>
             <td ><a>{{product.name}}</a></td><br>
             <td ><a>{{product.description}}</a></td><br>
             <td ><a>{{ product.price }}р</a></td><br>
         </tr>
        <tbody/>
    </table>


<form action="{% url 'cart:basket_add' product.id %}" method="post">
    {{ cart_product_form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Add to cart">
</form>

<form class="container" action="{% url 'sweet:home' %}">
      <button>Продолжить покупки</button>
</form>

<form class="container" action="{% url 'cart:basket' %}">
      <button>Перейти в корзину</button>
</form>


{% endif %}

{% endblock %}